# This is an example of a custom Tekton task that can be used in both build and review pipelines.
# Modify this template to fit your specific task requirements or use it as a base for creating custom configurations.
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  params:
  - name: BASE_IMAGE
    type: string
    default: "alpine"
  - name: username
    type: string
  workspaces:
    - description: A workspace that contains fetched git repo.
      name: source
  steps:
    - name: hello-world
      image: $(params.BASE_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo "Hello $(params.username), the repository contains the following files:"
        ls -al
