apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    # -- Required label to identify the pipeline type as "review".
    app.edp.epam.com/pipelinetype: review
    {{- include "edp-tekton.labels" . | nindent 4 }}
  name: gerrit-review
spec:
  description: The Review pipeline template for validating changes from Gerrit repositories.
    This template also demonstrates how to extend the pipeline with custom tasks, including the custom task "hello-world".

  # -- Parameters for the pipeline, automatically injected by the Tekton Trigger Template.
  params:
    - default: https://portal-{{ $.Release.Namespace }}.{{ $.Values.dnsWildCard }}/c/main/pipelines/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)
      name: pipelineUrl
      type: string
    - default: https://github.com/epmd-edp/python-python-python-3.8
      description: git url to clone
      name: git-source-url
      type: string
    - default: master
      description: git revision to checkout (branch, tag, sha, ref…)
      name: git-source-revision
      type: string
    - default: ''
      description: Refspec to fetch before checking out revision.
      name: git-refspec
      type: string
    - default: python-app
      description: Project name
      name: CODEBASE_NAME
      type: string
    - description: Target branch of Merge Request
      name: targetBranch
      type: string
    - description: Change number from Merge Request
      name: changeNumber
      type: string
    - description: Patchset number from Merge Request
      name: patchsetNumber
      type: string

    # -- Example of custom parameters that may be utilized within Tekton tasks.
    - default: "World"
      description: "Example parameter"
      name: username
      type: string
    - default: 'alpine:3.18.9'
      name: image-version
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-source-url)
        - name: revision
          value: $(params.git-source-revision)
        - name: refspec
          value: $(params.git-refspec)
        - name: subdirectory
          value: source
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ssh-creds
    - name: gerrit-notify
      params:
        - name: GERRIT_PORT
          value: '30020'
        - name: SSH_GERRIT_COMMAND
          value: >-
            review --verified 0 --message 'Build Started $(params.pipelineUrl)'
            $(params.changeNumber),$(params.patchsetNumber)
      taskRef:
        kind: Task
        name: gerrit-ssh-cmd
      workspaces:
        - name: ssh-directory
          workspace: ssh-creds
    - name: init-values
      params:
        - name: CODEBASE_NAME
          value: $(params.CODEBASE_NAME)
        - name: BRANCH_NAME
          value: $(params.targetBranch)
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: init-values

    # -- Example of a custom task added to the pipeline.
    # This task demonstrates how to include custom tasks in the pipeline.
    # It can be adapted to meet specific requirements by modifying or adding custom logic.
    - name: hello-world
      taskRef:
        name: hello-world
      runAfter:
        - init-values
      params:
        - name: BASE_IMAGE
          value: "$(params.image-version)"
        - name: username
          value: "$(params.username)"
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  finally:
    - name: gerrit-vote-success
      params:
        - name: GERRIT_PORT
          value: '30020'
        - name: SSH_GERRIT_COMMAND
          value: >-
            review --verified +1 --message 'Build Successfull
            $(params.pipelineUrl)'
            $(params.changeNumber),$(params.patchsetNumber)
      taskRef:
        kind: Task
        name: gerrit-ssh-cmd
      when:
        - input: $(tasks.status)
          operator: in
          values:
            - Succeeded
      workspaces:
        - name: ssh-directory
          workspace: ssh-creds
    - name: gerrit-vote-failure
      params:
        - name: GERRIT_PORT
          value: '30020'
        - name: SSH_GERRIT_COMMAND
          value: >-
            review --verified -1 --message 'Build Failed $(params.pipelineUrl)'
            $(params.changeNumber),$(params.patchsetNumber)
      taskRef:
        kind: Task
        name: gerrit-ssh-cmd
      when:
        - input: $(tasks.status)
          operator: in
          values:
            - Failed
      workspaces:
        - name: ssh-directory
          workspace: ssh-creds
